/* gknsoftware.com — soru kutusu.
   Sağ altta duran düğmeye basınca açılıyor, soruyu gokhan.ai'ye gönderiyor. */
(function () {
  var UC = 'https://gokhan-ai.onrender.com/api/sor';
  var dil = (document.documentElement.lang || 'tr').slice(0, 2);
  if (['tr', 'en', 'de'].indexOf(dil) < 0) dil = 'tr';

  var T = {
    tr: { dugme:'Soru sorun', baslik:'gokhan.ai\'ye sorun',
      alt:'Hizmetlerimiz hakkında merak ettiğinizi yazın, yapay zeka yanıtlasın.',
      ph:'Sorunuzu yazın…',
      gonder:'Sor', dusunuyor:'Yanıt hazırlanıyor…', kapat:'Kapat',
      uyari:'Yanıtlar yapay zeka tarafından üretiliyor; bağlayıcı teklif değildir.',
      hata:'Şu an ulaşılamıyor. İletişim sayfasından bize yazabilirsiniz.',
      ornekler:['Rücu takip sistemi ne yapıyor?','Microsoft 365 göçü yapıyor musunuz?',
                'Verimiz kurum içinde kalabilir mi?','Sadece destek anlaşması olur mu?'] },
    en: { dugme:'Ask a question', baslik:'Ask gokhan.ai',
      alt:'Type what you want to know about our services and the AI will answer.',
      ph:'Type your question…',
      gonder:'Ask', dusunuyor:'Preparing an answer…', kapat:'Close',
      uyari:'Answers are generated by AI and are not a binding quote.',
      hata:'Not reachable right now. Please write to us from the contact page.',
      ornekler:['What does the recourse system do?','Do you handle Microsoft 365 migration?',
                'Can our data stay in-house?','Can we take support only?'] },
    de: { dugme:'Frage stellen', baslik:'gokhan.ai fragen',
      alt:'Schreiben Sie, was Sie über unsere Leistungen wissen möchten — die KI antwortet.',
      ph:'Ihre Frage…',
      gonder:'Fragen', dusunuyor:'Antwort wird vorbereitet…', kapat:'Schließen',
      uyari:'Antworten stammen von einer KI und sind kein verbindliches Angebot.',
      hata:'Derzeit nicht erreichbar. Bitte schreiben Sie uns über die Kontaktseite.',
      ornekler:['Was macht die Regressverwaltung?','Übernehmen Sie Microsoft-365-Migrationen?',
                'Können unsere Daten im Haus bleiben?','Geht auch nur ein Supportvertrag?'] }
  }[dil];

  function E(s) {
    return String(s == null ? '' : s).replace(/&/g,'&amp;').replace(/</g,'&lt;')
      .replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  }
  function md(s) {
    var html = E(s).replace(/\*\*(.+?)\*\*/g, '<b>$1</b>');
    var satir = html.split('\n'), out = '', liste = false;
    for (var i = 0; i < satir.length; i++) {
      var t = satir[i].trim();
      if (/^[-*]\s+/.test(t)) {
        if (!liste) { out += '<ul>'; liste = true; }
        out += '<li>' + t.replace(/^[-*]\s+/, '') + '</li>';
      } else {
        if (liste) { out += '</ul>'; liste = false; }
        if (t) out += '<p>' + t + '</p>';
      }
    }
    if (liste) out += '</ul>';
    return out;
  }

  var kabuk = document.createElement('div');
  kabuk.className = 'sor-kabuk';
  kabuk.innerHTML =
    '<button class="sor-dugme" type="button" aria-expanded="false">' +
      '<svg width="17" height="17" viewBox="0 0 64 64" fill="none" aria-hidden="true">' +
      '<path d="M27 12 H24 Q22 12 22 14.5 V27 Q22 32 14 32 Q22 32 22 37 V49.5 Q22 52 24 52 H27" ' +
      'stroke="currentColor" stroke-width="5.6" stroke-linecap="round" stroke-linejoin="round"/>' +
      '<path d="M37 12 H40 Q42 12 42 14.5 V27 Q42 32 50 32 Q42 32 42 37 V49.5 Q42 52 40 52 H37" ' +
      'stroke="currentColor" stroke-width="5.6" stroke-linecap="round" stroke-linejoin="round"/>' +
      '<circle cx="32" cy="32" r="6.4" fill="currentColor"/></svg>' +
      '<span>' + E(T.dugme) + '</span></button>' +
    '<div class="sor-panel" hidden>' +
      '<div class="sor-bas"><div><b>' + E(T.baslik) + '</b><span>' + E(T.alt) + '</span></div>' +
        '<button class="sor-kapat" type="button" aria-label="' + E(T.kapat) + '">&times;</button></div>' +
      '<div class="sor-govde"><div class="sor-ornek">' +
        T.ornekler.map(function (o) { return '<button type="button">' + E(o) + '</button>'; }).join('') +
      '</div></div>' +
      '<form class="sor-alt"><textarea rows="1" maxlength="400" placeholder="' + E(T.ph) + '"></textarea>' +
        '<button class="sor-gonder" type="submit">' + E(T.gonder) + '</button></form>' +
      '<div class="sor-uyari">' + E(T.uyari) + '</div>' +
    '</div>';
  document.body.appendChild(kabuk);

  var dugme = kabuk.querySelector('.sor-dugme'),
      panel = kabuk.querySelector('.sor-panel'),
      govde = kabuk.querySelector('.sor-govde'),
      form  = kabuk.querySelector('.sor-alt'),
      alan  = kabuk.querySelector('textarea'),
      gonder = kabuk.querySelector('.sor-gonder');

  function ac(v) {
    panel.hidden = !v;
    dugme.setAttribute('aria-expanded', v ? 'true' : 'false');
    kabuk.classList.toggle('acik', v);
    if (v) setTimeout(function () { alan.focus(); }, 60);
  }
  dugme.addEventListener('click', function () { ac(panel.hidden); });
  kabuk.querySelector('.sor-kapat').addEventListener('click', function () { ac(false); });
  document.addEventListener('keydown', function (e) { if (e.key === 'Escape') ac(false); });

  govde.addEventListener('click', function (e) {
    var b = e.target.closest ? e.target.closest('.sor-ornek button') : null;
    if (b) { alan.value = b.textContent; gonderSoru(); }
  });

  alan.addEventListener('input', function () {
    alan.style.height = 'auto';
    alan.style.height = Math.min(alan.scrollHeight, 110) + 'px';
  });
  alan.addEventListener('keydown', function (e) {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); gonderSoru(); }
  });
  form.addEventListener('submit', function (e) { e.preventDefault(); gonderSoru(); });

  function ekle(sinif, html) {
    var d = document.createElement('div');
    d.className = 'sor-' + sinif;
    d.innerHTML = html;
    govde.appendChild(d);
    govde.scrollTop = govde.scrollHeight;
    return d;
  }

  var mesgul = false;
  function gonderSoru() {
    var soru = alan.value.trim();
    if (!soru || mesgul) return;
    var ornek = govde.querySelector('.sor-ornek');
    if (ornek) ornek.parentNode.removeChild(ornek);

    mesgul = true; gonder.disabled = true;
    alan.value = ''; alan.style.height = 'auto';
    ekle('soru', E(soru));
    var bekle = ekle('bekle', E(T.dusunuyor));

    fetch(UC, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ soru: soru, dil: dil })
    }).then(function (r) { return r.json(); })
      .then(function (d) {
        bekle.parentNode.removeChild(bekle);
        if (d && d.cevap) ekle('cevap', md(d.cevap));
        else ekle('uyari-satir', E((d && d.error) || T.hata));
      })
      .catch(function () {
        if (bekle.parentNode) bekle.parentNode.removeChild(bekle);
        ekle('uyari-satir', E(T.hata));
      })
      .then(function () { mesgul = false; gonder.disabled = false; alan.focus(); });
  }
})();
